#ifndef _CONSTANTS
#define _CONSTANTS
// WALL DISTANCE SENSIBILITY CONSTANTS (mm)
#define SIDE_WALL_DIST 60
#define FRONT_WALL_DIST 60
// WALL DISTANCE OFFSET CONSTANTS (mm)
#define TOF_OFFSET 10

#endif